app:
  scheduler:
    enable: true
    interval: 10000
    force-check-delay: 10s
    seconds-threshold: 60
  database-access-type: jpa
  use-queue: true
  kafka:
    bootstrap-servers: localhost:9092
    topic-name: bot-updates

spring:
  application:
    name: scrapper
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: false

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
  level:
    root: DEBUG

api:
  bot:
    baseUrl: http://localhost:8090
    backOffType: CONSTANT
    retryCount: 3
    retryInterval: 1
    statuses: INTERNAL_SERVER_ERROR, BAD_GATEWAY, INSUFFICIENT_STORAGE, SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT
  github:
    baseUrl: https://api.github.com
    backOffType: CONSTANT
    retryCount: 3
    retryInterval: 1
    statuses: INTERNAL_SERVER_ERROR, BAD_GATEWAY, INSUFFICIENT_STORAGE, SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT
  stackoverflow:
    baseUrl: https://api.stackexchange.com/2.3
    backOffType: CONSTANT
    retryCount: 3
    retryInterval: 1
    statuses: INTERNAL_SERVER_ERROR, BAD_GATEWAY, INSUFFICIENT_STORAGE, SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT

springdoc:
  swagger-ui:
    path: /swagger-ui

bucket:
  queryCount: 15
