app:
  scheduler:
    enable: true
    interval: 10000
    force-check-delay: 10s
    seconds-threshold: 60
  database-access-type: jdbc

spring:
  application:
    name: scrapper
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: false

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
  level:
    root: DEBUG

api:
  bot:
    baseUrl: http://localhost:8090
  github:
    baseUrl: https://api.github.com
  stackoverflow:
    baseUrl: https://api.stackexchange.com/2.3

springdoc:
  swagger-ui:
    path: /swagger-ui
