app:
  telegram-token: ${TELEGRAM_TOKEN}
  kafka:
    bootstrap-servers: localhost:9092
    group-id: bot-messages
    topicName: bot-updates
    bad-response-topic-name: bot-updates_dlq

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
  level:
      root: DEBUG

api:
  scrapper:
    baseUrl: http://localhost:8080
    backOffType: CONSTANT
    retryCount: 3
    retryInterval: 1
    statuses: INTERNAL_SERVER_ERROR, BAD_GATEWAY, INSUFFICIENT_STORAGE, SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT

springdoc:
  swagger-ui:
    path: /swagger-ui

bucket:
  queryCount: 15
