app:
  telegram-token: ${TELEGRAM_TOKEN}

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
  level:
      root: DEBUG

api:
  scrapper:
    baseUrl: http://localhost:8080

springdoc:
  swagger-ui:
    path: /swagger-ui
